# documentation: https://docs.hyperfy.io/
# slogan: A high-performance 3D metaverse platform using Three.js and React
# tags: metaverse,3d,threejs,react,gaming
# logo: svgs/hyperfy.svg
# port: 3000

version: '3.8'

services:
  app:
    image: howieduhzit/hyperfy:main
    environment:
      - WORLD=world
      - PORT=3000
      - JWT_SECRET=hyper
      - ADMIN_CODE=admin
      - SAVE_INTERVAL=60
      - PUBLIC_MAX_UPLOAD_SIZE=12
      - PUBLIC_WS_URL=${SERVICE_FQDN_HYPERFY}/ws
      - PUBLIC_API_URL=${SERVICE_FQDN_HYPERFY}/api
      - PUBLIC_ASSETS_URL=${SERVICE_FQDN_HYPERFY}/assets
    volumes:
      - app:/app