# documentation: https://docs.hyperfy.io/
# slogan: A high-performance 3D metaverse platform using Three.js and React
# tags: metaverse,3d,threejs,react,gaming
# logo: svgs/hyperfy.svg
# port: 3000

version: '3.8'

services:
  hyperfy:
    image: howieduhzit/hyperfy:main
    environment:
      - WORLD=${WORLD:-world}
      - PORT=${PORT:-3000}
      - JWT_SECRET=${JWT_SECRET:-hyper}
      - ADMIN_CODE=${ADMIN_CODE:-admin}
      - SAVE_INTERVAL=${SAVE_INTERVAL:-60}
      - PUBLIC_MAX_UPLOAD_SIZE=${PUBLIC_MAX_UPLOAD_SIZE:-12}
      - PUBLIC_WS_URL=${COOLIFY_URL}/ws
      - PUBLIC_API_URL=${COOLIFY_URL}/api
      - PUBLIC_ASSETS_URL=${COOLIFY_URL}/assets
    volumes:
      - world:/:/app/world